name: Object Storage Upload
run-name: Upload to Yandex Cloud 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - uses: nekitcorp/yandex-storage-website-action@v2
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          working-directory: dist
          clear: true
